export interface Track {
  id: string;
  title: string;
  artist: string;
  duration: number; // in seconds
  videoId: string; // YouTube video ID
}

export interface Playlist {
  id: string;
  name: string;
  nameLocal: string; // Bengali/local name
  tracks: Track[];
}

// IMPORTANT: Add YouTube video IDs for each track
// Find videos at: youtube.com/results?search_query=[song+title]+[artist]
// Make sure embedding is enabled for the video
// Replace the empty videoId strings with actual YouTube video IDs

export const playlists: Playlist[] = [
  {
    id: "daily-rock",
    name: "Daily Rock",
    nameLocal: "Daily Rock",
    tracks: [
      { id: "1", title: "Running Up That Hill", artist: "Kate Bush", duration: 305, videoId: "" },
      { id: "2", title: "Jo Tere Sang", artist: "Jeet Gannguli, Mustafa Zahid", duration: 270, videoId: "" },
      { id: "3", title: "Maan Meri Jaan", artist: "King", duration: 240, videoId: "" },
      { id: "4", title: "Locksmith", artist: "Sadie Jean", duration: 180, videoId: "" },
      { id: "5", title: "Aaya Na Tu", artist: "Arjun Kanungo, Momina Mustehsan", duration: 288, videoId: "" },
      { id: "6", title: "Dandelions", artist: "Ruth B.", duration: 225, videoId: "" },
      { id: "7", title: "Protect the Light", artist: "SPITZ", duration: 260, videoId: "" },
      { id: "8", title: "Lo Maan Liya", artist: "Arijit Singh", duration: 305, videoId: "" },
      { id: "9", title: "Golden Brown", artist: "The Stranglers", duration: 215, videoId: "" },
      { id: "10", title: "Mahiye Jinna Sohna", artist: "Darshan Raval", duration: 240, videoId: "" },
      { id: "11", title: "Co2", artist: "Prateek Kuhad", duration: 290, videoId: "" },
      { id: "12", title: "Mitwa", artist: "Shankar-Ehsaan-Loy", duration: 355, videoId: "" },
      { id: "13", title: "Mann Mera", artist: "Gajendra Verma", duration: 310, videoId: "" },
      { id: "14", title: "Raanjhanaa", artist: "A.R. Rahman, Jaswinder Singh", duration: 270, videoId: "" },
      { id: "15", title: "Ajab Si", artist: "KK, Vishal-Shekhar", duration: 330, videoId: "" },
      { id: "16", title: "Khuda Jaane", artist: "Vishal-Shekhar, KK", duration: 340, videoId: "" },
      { id: "17", title: "Tum Jo Aaye", artist: "Pritam, Tulsi Kumar", duration: 380, videoId: "" },
      { id: "18", title: "Dilbara", artist: "Pritam, Abhijeet", duration: 325, videoId: "" },
      { id: "19", title: "Falak Tak", artist: "Vishal-Shekhar, Udit Narayan", duration: 420, videoId: "" },
      { id: "20", title: "Kya Mujhe Pyar Hai", artist: "Pritam, KK", duration: 310, videoId: "" },
      { id: "21", title: "Ek Din Teri Raahon", artist: "Javed Ali, Pritam", duration: 235, videoId: "" },
      { id: "22", title: "Haan Tu Hain", artist: "Pritam, KK", duration: 300, videoId: "" },
      { id: "23", title: "Last Christmas", artist: "Wham!", duration: 244, videoId: "" },
      { id: "24", title: "Tera Hone Laga Hoon", artist: "Pritam, Atif Aslam", duration: 270, videoId: "" },
      { id: "25", title: "7 Years", artist: "Lukas Graham", duration: 273, videoId: "" },
      { id: "26", title: "Sahiba", artist: "Aditya Rikhari", duration: 290, videoId: "" },
      { id: "27", title: "SNAP", artist: "Rosa Linn", duration: 240, videoId: "" },
      { id: "28", title: "Tum Se Hi", artist: "Pritam, Mohit Chauhan", duration: 240, videoId: "" },
      { id: "29", title: "Aadat", artist: "Atif Aslam, Jal", duration: 273, videoId: "" },
      { id: "30", title: "Billie Jean", artist: "Michael Jackson", duration: 294, videoId: "" },
      { id: "31", title: "They Don't Care About Us", artist: "Michael Jackson", duration: 361, videoId: "" },
      { id: "32", title: "Tu Jaane Na", artist: "Pritam, Atif Aslam", duration: 230, videoId: "" },
      { id: "33", title: "Pee Loon", artist: "Pritam, Mohit Chauhan", duration: 280, videoId: "" },
      { id: "34", title: "Zaalima", artist: "Arijit Singh, Harshdeep Kaur", duration: 240, videoId: "" },
      { id: "35", title: "Raabta", artist: "Pritam, Arijit Singh", duration: 320, videoId: "" },
      { id: "36", title: "Pehli Dafa", artist: "Atif Aslam, Shiraz Uppal", duration: 260, videoId: "" },
      { id: "37", title: "Ik Kahani", artist: "Gajendra Verma", duration: 190, videoId: "" },
      { id: "38", title: "Darasal", artist: "Atif Aslam, Jam8", duration: 250, videoId: "" },
      { id: "39", title: "Tere Bina", artist: "A.R. Rahman, Chinmayi", duration: 330, videoId: "" },
      { id: "40", title: "Kabhi Kabhi Aditi", artist: "Rashid Ali", duration: 220, videoId: "" },
      { id: "41", title: "Main Rang Sharbaton Ka", artist: "Atif Aslam, Chinmayi", duration: 280, videoId: "" },
      { id: "42", title: "O Saathi", artist: "Atif Aslam, Arko", duration: 240, videoId: "" },
      { id: "43", title: "Mere Bina", artist: "Pritam, Nikhil D'Souza", duration: 270, videoId: "" },
      { id: "44", title: "The Night We Met", artist: "Lord Huron, Phoebe Bridgers", duration: 300, videoId: "" },
      { id: "45", title: "Tera Ghata", artist: "Gajendra Verma", duration: 205, videoId: "" },
      { id: "46", title: "Malang Sajna", artist: "Sachet Tandon, Parampara Tandon", duration: 240, videoId: "" },
      { id: "47", title: "Sanam Teri Kasam", artist: "Himesh Reshammiya, Ankit Tiwari", duration: 240, videoId: "" },
      { id: "48", title: "Tujhe Bhula Diya", artist: "Vishal-Shekhar, Mohit Chauhan", duration: 260, videoId: "" },
      { id: "49", title: "Samjho Na", artist: "Aditya Rikhari", duration: 310, videoId: "" },
      { id: "50", title: "Sajni", artist: "Ram Sampath, Arijit Singh", duration: 310, videoId: "" },
      { id: "51", title: "Chahun Main Ya Naa", artist: "Palak Muchhal, Arijit Singh", duration: 250, videoId: "" },
      { id: "52", title: "Ishq", artist: "Faheem Abdullah, Rauhan Malik", duration: 220, videoId: "" },
      { id: "53", title: "Khuda Haafiz", artist: "Vishal Dadlani", duration: 290, videoId: "" },
      { id: "54", title: "Until I Found You", artist: "Stephen Sanchez", duration: 208, videoId: "" },
      { id: "55", title: "Love Me Like You Do", artist: "Ellie Goulding", duration: 241, videoId: "" },
      { id: "56", title: "Papaoutai", artist: "Stromae", duration: 266, videoId: "" },
      { id: "57", title: "Papaoutai (Afro Soul)", artist: "Chill77, Unjaps", duration: 280, videoId: "" },
      { id: "58", title: "Kaise Hua", artist: "Vishal Mishra, Manoj Muntashir", duration: 270, videoId: "" },
      { id: "59", title: "Pehli Nazar Mein", artist: "Atif Aslam, Pritam", duration: 270, videoId: "" },
      { id: "60", title: "Somewhere Only We Know", artist: "Keane", duration: 223, videoId: "" },
      { id: "61", title: "back to friends", artist: "sombr", duration: 190, videoId: "" },
      { id: "62", title: "I Don't Know (Radio Mix)", artist: "Erika", duration: 210, videoId: "" },
      { id: "63", title: "Saware", artist: "Pritam, Arijit Singh", duration: 310, videoId: "" },
      { id: "64", title: "Let It Happen", artist: "Tame Impala", duration: 326, videoId: "" },
      { id: "65", title: "Following the Sun", artist: "SUPER-Hi, NEEKA", duration: 240, videoId: "" },
      { id: "66", title: "Following The Sun (2026)", artist: "SUPER-Hi, NEEKA", duration: 240, videoId: "" },
      { id: "67", title: "I Think They Call This Love", artist: "Matthew Ifield", duration: 220, videoId: "" },
      { id: "68", title: "Let Me Love You", artist: "DJ Snake, Justin Bieber", duration: 212, videoId: "" },
      { id: "69", title: "Con la Misma Piedra", artist: "Julio Iglesias", duration: 210, videoId: "" },
      { id: "70", title: "Channa Ve", artist: "Akhil Sachdeva, Mansheel Gujral", duration: 270, videoId: "" },
      { id: "71", title: "Gulabi Aankhen", artist: "Sanam", duration: 240, videoId: "" },
      { id: "72", title: "Tera Mujhse", artist: "Kishore Kumar, Sushma Shrestha", duration: 220, videoId: "" },
    ],
  },
  {
    id: "songeet",
    name: "সংগীত",
    nameLocal: "সংগীত",
    tracks: [
      { id: "1", title: "O Chand", artist: "Rupankar Bagchi", duration: 340, videoId: "" },
      { id: "2", title: "Boba Tunnel", artist: "Anupam Roy", duration: 300, videoId: "" },
      { id: "3", title: "Bariye Dao", artist: "Anupam Roy", duration: 280, videoId: "" },
      { id: "4", title: "Ekhon Onek Raat", artist: "Anupam Roy", duration: 310, videoId: "" },
      { id: "5", title: "Amake Aamar Moto Thaakte Dao", artist: "Anupam Roy", duration: 280, videoId: "" },
      { id: "6", title: "Ekbar Bol", artist: "Anupam Roy", duration: 230, videoId: "" },
      { id: "7", title: "Amar Bhindeshi Tara", artist: "Chandrabindoo", duration: 240, videoId: "" },
      { id: "8", title: "Cigarette", artist: "Anjan Dutt", duration: 190, videoId: "" },
      { id: "9", title: "Tumi Na Thakle", artist: "Anjan Dutt, Usha Uthup", duration: 280, videoId: "" },
      { id: "10", title: "Benche Thakar Gaan", artist: "Rupam Islam, Anupam Roy", duration: 310, videoId: "" },
      { id: "11", title: "Barandaye Roddur", artist: "Bhoomi", duration: 240, videoId: "" },
      { id: "12", title: "Ami Sudhu Khujechi Amay", artist: "Taalpatar Shepai", duration: 280, videoId: "" },
      { id: "13", title: "Ranjana Ami Ar Ashbona", artist: "Anjan Dutt", duration: 220, videoId: "" },
      { id: "14", title: "December'er Shohorey", artist: "Sourav Saha", duration: 300, videoId: "" },
      { id: "15", title: "Jawl Phoring", artist: "Silajit, Anupam Roy", duration: 320, videoId: "" },
      { id: "16", title: "Moshader Chumu", artist: "Taalpatar Shepai", duration: 260, videoId: "" },
      { id: "17", title: "Prithibi Ta Naki Chhoto Hote Hote", artist: "Crosswinds", duration: 240, videoId: "" },
      { id: "18", title: "Mor Bhabonare Ki Haoway", artist: "Somlata Acharyya Chowdhury", duration: 280, videoId: "" },
      { id: "19", title: "Ghore Pherar Gaan", artist: "Mohiner Ghoraguli", duration: 270, videoId: "" },
      { id: "20", title: "Tomake Chai", artist: "Kabir Suman", duration: 230, videoId: "" },
      { id: "21", title: "Melar Gaan", artist: "Hooligaanism, Anirban Bhattacharya", duration: 290, videoId: "" },
      { id: "22", title: "Mayabono Biharini", artist: "Somlata Acharyya Chowdhury, Rupam Islam", duration: 300, videoId: "" },
      { id: "23", title: "2441139 (Bela Bose)", artist: "Anjan Dutt, Neel Dutt", duration: 260, videoId: "" },
      { id: "24", title: "Mayabini", artist: "Zubeen Garg", duration: 240, videoId: "" },
      { id: "25", title: "Ei Srabon", artist: "Rupam Islam, Anupam Roy", duration: 310, videoId: "" },
      { id: "26", title: "The Rum Song", artist: "The Frisbees Music, Nabarun Bose", duration: 250, videoId: "" },
      { id: "27", title: "Aami Ashbo Phirey", artist: "Neel Dutt", duration: 280, videoId: "" },
      { id: "28", title: "Aaj Ei Dintake", artist: "Kishore Kumar", duration: 230, videoId: "" },
      { id: "29", title: "Tomake Chai", artist: "Arijit Singh, Arindom", duration: 320, videoId: "" },
      { id: "30", title: "Egiye De", artist: "Arindom, Arijit Singh, Madhubanti Bagchi", duration: 300, videoId: "" },
    ],
  },
  {
    id: "bangla-folk",
    name: "Bangla FOLK",
    nameLocal: "Bangla FOLK",
    tracks: [
      { id: "1", title: "Dayal Baba", artist: "Koushik Chakraborty", duration: 320, videoId: "" },
      { id: "2", title: "Tomar Ghore Bosot Kore", artist: "Rishi Panda", duration: 280, videoId: "" },
      { id: "3", title: "Kalo Jwole Kuchla Tole", artist: "Rishi Panda", duration: 240, videoId: "" },
      { id: "4", title: "Lal Paharir Deshe Ja", artist: "Bhoomi", duration: 290, videoId: "" },
      { id: "5", title: "Phagooner Mohonaye", artist: "Bhoomi", duration: 310, videoId: "" },
      { id: "6", title: "Pal Tule De", artist: "The Folk Diaryz", duration: 260, videoId: "" },
      { id: "7", title: "Agun Lagaiya Dilo Kone", artist: "The Folk Diaryz", duration: 270, videoId: "" },
      { id: "8", title: "Bokul Ful", artist: "The Folk Diaryz", duration: 280, videoId: "" },
      { id: "9", title: "Pindare Polaser Bon", artist: "Poushali Banerjee", duration: 240, videoId: "" },
      { id: "10", title: "Golemale Golemale Pirit Koro Na", artist: "Bhoomi", duration: 300, videoId: "" },
      { id: "11", title: "Sohag Chand Badoni", artist: "Babul Supriyo", duration: 320, videoId: "" },
      { id: "12", title: "Khachar Vitar Achin Pakhi", artist: "Kartik Das Baul", duration: 280, videoId: "" },
      { id: "13", title: "Age Ki Sundor Din Kataitam", artist: "The Folk Diaryz", duration: 310, videoId: "" },
      { id: "14", title: "Milon Hobe Koto Dine", artist: "TAPOSH", duration: 240, videoId: "" },
      { id: "15", title: "Komola", artist: "Ankita Bhattacharyya", duration: 260, videoId: "" },
      { id: "16", title: "Mone Kori Assam Jabo", artist: "Tanmay Kar and Friends", duration: 290, videoId: "" },
      { id: "17", title: "Bonde Maya Lagaiche", artist: "Shankha Banik Chowdhury, Azhar Sk", duration: 300, videoId: "" },
      { id: "18", title: "Pindare Polasher Bon", artist: "Teetas", duration: 270, videoId: "" },
      { id: "19", title: "Menoka Mathaye Dilo", artist: "Bhoomi", duration: 250, videoId: "" },
      { id: "20", title: "Nizamuddin", artist: "Fakira", duration: 240, videoId: "" },
      { id: "21", title: "Nesha Lagilo", artist: "Iman Chakraborty", duration: 280, videoId: "" },
      { id: "22", title: "Leelabali", artist: "Lopamudra Mitra", duration: 320, videoId: "" },
      { id: "23", title: "Sob Loke Koy Lalon", artist: "Fakira", duration: 260, videoId: "" },
      { id: "24", title: "Tomra Kunjo Sajao Go", artist: "Dipannita Acharya", duration: 240, videoId: "" },
      { id: "25", title: "O Shib Nacho Re", artist: "The Folk Diaryz", duration: 290, videoId: "" },
      { id: "26", title: "Thakile Dobakhana", artist: "The Folk Diaryz", duration: 280, videoId: "" },
      { id: "27", title: "Golemele Pirit Korona", artist: "The Folk Diaryz", duration: 270, videoId: "" },
      { id: "28", title: "Khepa Shib", artist: "The Folk Diaryz", duration: 240, videoId: "" },
      { id: "29", title: "Piriti Koirase Dewana", artist: "The Folk Diaryz", duration: 310, videoId: "" },
      { id: "30", title: "Dube Dakh Dakhi Mon", artist: "The Folk Diaryz", duration: 280, videoId: "" },
    ],
  },
  {
    id: "bangla-gaan",
    name: "বাংলা গান",
    nameLocal: "বাংলা গান",
    tracks: [
      { id: "1", title: "Ami Deshlai", artist: "Death By Anjuna, Murshidabadi", duration: 280, videoId: "" },
      { id: "2", title: "Gopono Kothati", artist: "Sauparna Manna, Devlinaa Adhikary", duration: 290, videoId: "" },
      { id: "3", title: "Pinik", artist: "Death By Anjuna", duration: 260, videoId: "" },
      { id: "4", title: "Loke Bole", artist: "Naved Parvez, Dripto", duration: 240, videoId: "" },
      { id: "5", title: "Ek Minute Er Chumu", artist: "Debraj Bhattacharya, Hooligaanism", duration: 270, videoId: "" },
      { id: "6", title: "Tomar Chokhe Dekhechi", artist: "The National Beats", duration: 300, videoId: "" },
      { id: "7", title: "BBD Bagh", artist: "Ujaan Ganguly, Debayan Banerjee", duration: 310, videoId: "" },
      { id: "8", title: "Gulbahar", artist: "Ishaan, Shuvendu Das Shuvo", duration: 280, videoId: "" },
      { id: "9", title: "Kaan Pete Shono", artist: "Naved Parvez, Fahad Bin Aziz", duration: 250, videoId: "" },
      { id: "10", title: "Ekhon Onek Raat", artist: "Anupam Roy", duration: 310, videoId: "" },
      { id: "11", title: "Tomar Ghawre Bawshot Kawre", artist: "Rapurna Bhattacharya, Amit Chatterjee", duration: 290, videoId: "" },
      { id: "12", title: "Chotto E Jibone", artist: "Rafi Alam", duration: 240, videoId: "" },
      { id: "13", title: "Jhiko Jhiko Kori Re", artist: "Krosswindz", duration: 280, videoId: "" },
      { id: "14", title: "Jene Nio", artist: "Ishaan, Nandita Mahmood", duration: 300, videoId: "" },
      { id: "15", title: "Bandhu Bhabi", artist: "Upal Sengupta", duration: 260, videoId: "" },
      { id: "16", title: "Tumi Bawdol Hoye Esho", artist: "Anirban Bhattacharya", duration: 310, videoId: "" },
      { id: "17", title: "Ga Chuye Bolo", artist: "Tanjib Sarowar, Abanti Sithi", duration: 280, videoId: "" },
      { id: "18", title: "Benche Thakar Gaan", artist: "Anupam Roy, Rupam Islam", duration: 320, videoId: "" },
      { id: "19", title: "Upo", artist: "Hatirpool Sessions", duration: 240, videoId: "" },
      { id: "20", title: "Hok Kolorob", artist: "Arnob", duration: 290, videoId: "" },
      { id: "21", title: "Kichchu Chaini Aami", artist: "Anirban Bhattacharya", duration: 270, videoId: "" },
      { id: "22", title: "Raikamal", artist: "Chakropani Dev, Debdeep Banik", duration: 330, videoId: "" },
      { id: "23", title: "Abar Phire Ele", artist: "Arijit Singh, Anupam Roy", duration: 310, videoId: "" },
      { id: "24", title: "Shey Jey Boshey Achey", artist: "Arnob", duration: 280, videoId: "" },
      { id: "25", title: "Ekul Bhange Okul Gawre", artist: "Arko", duration: 260, videoId: "" },
      { id: "26", title: "Bojhena Shey Bojhena", artist: "Arijit Singh, Indraadip Dasgupta", duration: 340, videoId: "" },
      { id: "27", title: "Bhule Jeo", artist: "Arindom, Amrita Singh", duration: 290, videoId: "" },
      { id: "28", title: "Eita Tomar Gaan", artist: "Chandrabindoo", duration: 240, videoId: "" },
      { id: "29", title: "Preme Pora Baron", artist: "Lagnajita Chakraborty", duration: 270, videoId: "" },
      { id: "30", title: "Shondhye Namar Aagey", artist: "Ishan Mitra, SaQi", duration: 300, videoId: "" },
    ],
  },
  {
    id: "bolly-2000s",
    name: "Bolly 2000s",
    nameLocal: "Bolly 2000s",
    tracks: [
      { id: "1", title: "Woh Lamhe Woh Baatein", artist: "Atif Aslam", duration: 340, videoId: "" },
      { id: "2", title: "Main Hoon Na", artist: "Sonu Nigam, Shreya Ghoshal", duration: 280, videoId: "" },
      { id: "3", title: "Tumhe Jo Maine Dekha", artist: "Abhijeet, Shreya Ghoshal", duration: 300, videoId: "" },
      { id: "4", title: "Tumse Milke Dil Ka", artist: "Sonu Nigam, Sabri Brothers", duration: 290, videoId: "" },
      { id: "5", title: "Phir Mohabbat", artist: "Mohammed Irfan, Arijit Singh", duration: 310, videoId: "" },
      { id: "6", title: "Bheegey Hont", artist: "Kunal Ganjawala", duration: 240, videoId: "" },
      { id: "7", title: "Mainu Tere Naal", artist: "Najam Sheraz", duration: 260, videoId: "" },
      { id: "8", title: "Shukran Allah", artist: "Salim–Sulaiman, Sonu Nigam", duration: 350, videoId: "" },
      { id: "9", title: "Main Agar Kahoon", artist: "Sonu Nigam, Shreya Ghoshal", duration: 330, videoId: "" },
      { id: "10", title: "Ajab Si", artist: "KK, Vishal-Shekhar", duration: 330, videoId: "" },
      { id: "11", title: "Khuda Jaane", artist: "Vishal-Shekhar, KK", duration: 340, videoId: "" },
      { id: "12", title: "Aankhein Khuli", artist: "Jatin-Lalit, Lata Mangeshkar", duration: 420, videoId: "" },
      { id: "13", title: "Maula Mere Maula", artist: "Roop Kumar Rathod, Sayeed Quadri", duration: 300, videoId: "" },
      { id: "14", title: "Tu Hi Meri Shab Hai", artist: "KK", duration: 240, videoId: "" },
      { id: "15", title: "Chand Sifarish", artist: "Jatin-Lalit, Shaan, Kailash Kher", duration: 330, videoId: "" },
      { id: "16", title: "Tauba Tumhare Ishare", artist: "Abhijeet, Alka Yagnik", duration: 290, videoId: "" },
      { id: "17", title: "Jaane Kyon Log Pyar", artist: "Udit Narayan, Alka Yagnik", duration: 330, videoId: "" },
      { id: "18", title: "Suraj Hua Maddham", artist: "Sandesh Shandilya, Sonu Nigam", duration: 300, videoId: "" },
      { id: "19", title: "Bhool Bhulaiyaa", artist: "Pritam, Neeraj Shridhar", duration: 310, videoId: "" },
      { id: "20", title: "Dil De Diya Hai", artist: "Anand Raj Anand", duration: 240, videoId: "" },
      { id: "21", title: "Mauja Hi Mauja", artist: "Pritam, Mika Singh", duration: 320, videoId: "" },
      { id: "22", title: "Parda", artist: "Pritam, Sunidhi Chauhan", duration: 280, videoId: "" },
      { id: "23", title: "Aapka Kya Hoga", artist: "Mika Singh, Sunidhi Chauhan", duration: 290, videoId: "" },
      { id: "24", title: "Oh Girl You're Mine", artist: "Tarun Sagar, Alyssa Mendonsa", duration: 260, videoId: "" },
      { id: "25", title: "Papa Jag Jayega", artist: "Ritu Pathak, Neeraj Shridhar", duration: 280, videoId: "" },
      { id: "26", title: "Jalwa", artist: "Wajid, Sajid-Wajid", duration: 240, videoId: "" },
      { id: "27", title: "Hale Dil", artist: "Harshit Saxena, Various Artists", duration: 210, videoId: "" },
      { id: "28", title: "Jhalak Dikhla Ja", artist: "Himesh Reshammiya", duration: 270, videoId: "" },
      { id: "29", title: "Soniye", artist: "KK, Sunidhi Chauhan", duration: 220, videoId: "" },
      { id: "30", title: "Crazy Kiya Re", artist: "Pritam, Sunidhi Chauhan", duration: 300, videoId: "" },
    ],
  },
  {
    id: "nineties",
    name: "90s",
    nameLocal: "90s",
    tracks: [
      { id: "1", title: "Saathiya Bin Tere Dil Mane Na", artist: "Anand-Milind, Kumar Sanu", duration: 350, videoId: "" },
      { id: "2", title: "Ladki Badi Anjani Hai", artist: "Jatin-Lalit, Kumar Sanu", duration: 280, videoId: "" },
      { id: "3", title: "Kitna Haseen Chehra", artist: "Kumar Sanu", duration: 260, videoId: "" },
      { id: "4", title: "Dil Ka Aalam", artist: "Kumar Sanu, Madan Pal", duration: 240, videoId: "" },
      { id: "5", title: "Is Pyar Se Meri Taraf Na Dekho", artist: "Kumar Sanu", duration: 250, videoId: "" },
      { id: "6", title: "Tumsa Koi Pyaara", artist: "Kumar Sanu, Alka Yagnik", duration: 300, videoId: "" },
      { id: "7", title: "Mujhe Neend Na Aaye", artist: "Anuradha Paudwal, Udit Narayan", duration: 320, videoId: "" },
      { id: "8", title: "Dhiktana, Pt. 1", artist: "S. P. Balasubrahmanyam", duration: 240, videoId: "" },
      { id: "9", title: "Aaj Hai Sagaai", artist: "Jatin-Lalit, Abhijeet", duration: 280, videoId: "" },
      { id: "10", title: "Kuch Kuch Hota Hai", artist: "Jatin-Lalit, Udit Narayan", duration: 300, videoId: "" },
      { id: "11", title: "Saajanji Ghar Aaye", artist: "Jatin-Lalit, Kumar Sanu", duration: 340, videoId: "" },
      { id: "12", title: "Choodi Baji Hai", artist: "Udit Narayan, Alka Yagnik", duration: 270, videoId: "" },
      { id: "13", title: "Chand Chhupa Badal Mein", artist: "Udit Narayan, Alka Yagnik", duration: 300, videoId: "" },
      { id: "14", title: "Bholi Si Surat", artist: "Uttam Singh, Lata Mangeshkar", duration: 350, videoId: "" },
      { id: "15", title: "Ho Nahi Sakta", artist: "Udit Narayan, Anu Malik", duration: 310, videoId: "" },
      { id: "16", title: "Ajnabi Mujhko Itna Bata", artist: "Jatin-Lalit, Asha Bhosle", duration: 320, videoId: "" },
      { id: "17", title: "Pyaar Ke Kagaz Pe", artist: "Abhijeet, Sadhana Sargam", duration: 280, videoId: "" },
      { id: "18", title: "Kisi Din Banoongi Main", artist: "Alka Yagnik, Udit Narayan", duration: 290, videoId: "" },
      { id: "19", title: "Phool Maangu Na Bahaar Maangu", artist: "Alka Yagnik, Udit Narayan", duration: 300, videoId: "" },
      { id: "20", title: "Dholna", artist: "Uttam Singh, Lata Mangeshkar", duration: 360, videoId: "" },
      { id: "21", title: "Are Re Are", artist: "Uttam Singh, Lata Mangeshkar", duration: 340, videoId: "" },
      { id: "22", title: "Mere Khayalon Ki Malika", artist: "Abhijeet", duration: 270, videoId: "" },
      { id: "23", title: "Hum to Dil Se Haare", artist: "Udit Narayan, Alka Yagnik", duration: 310, videoId: "" },
      { id: "24", title: "Aaj Pehli Baar Dil Ki Baat", artist: "Kumar Sanu, Alka Yagnik", duration: 300, videoId: "" },
      { id: "25", title: "Tere Mere Honthon Pe Mitwa", artist: "Lata Mangeshkar, Babla Mehta", duration: 280, videoId: "" },
      { id: "26", title: "Lagi Aaj Sawan Ki", artist: "Suresh Wadkar, Anupama", duration: 240, videoId: "" },
      { id: "27", title: "Anar Dana", artist: "Lata Mangeshkar", duration: 200, videoId: "" },
      { id: "28", title: "Choodi Maza Na Degi", artist: "Lata Mangeshkar", duration: 220, videoId: "" },
      { id: "29", title: "O Hare Dupattewali", artist: "Vipin Sachdeva", duration: 240, videoId: "" },
      { id: "30", title: "Maine Payal Hai Chhankai", artist: "Falguni Pathak", duration: 300, videoId: "" },
    ],
  },
];

export function getPlaylistById(id: string): Playlist | undefined {
  return playlists.find((p) => p.id === id);
}

export function getTrackById(playlistId: string, trackId: string): Track | undefined {
  const playlist = getPlaylistById(playlistId);
  return playlist?.tracks.find((t) => t.id === trackId);
}
